In [14]:
# https://nbviewer.jupyter.org/   git 上不显示时， 复制文件链接到 nbviewer


import torch
# list to tensor
v_data = [1., 2., 3.]
v = torch.Tensor(v_data)
print(v)
print(v[0])
m_data = [[1., 2., 3.],[4., 5., 6.]]
m = torch.Tensor(m_data)
print(m)
print(m[0])
t_data = [[[1.,2.],[3., 4.]],
          [[5.,6.],[7., 8.]]]
t = torch.Tensor(t_data)
print(t)
print(t[0])

x = torch.randn((3, 4, 5))# 随机数
print(x)

# 张量间的数学运算
x = torch.Tensor([1.,2.,3.])
y = torch.Tensor([4.,5.,6.])
z = x + y
print(z)

# Tensor 的拼接, 默认基于第一个维度进行拼接
x1 = torch.randn(2, 5)
y1 = torch.randn(3, 5)
z1 = torch.cat([x1, y1])
print(z1)

x2 = torch.randn(2, 3)
y2 = torch.randn(2, 5)
z2 = torch.cat([x2, y2], 1) # 拼接的维度为1， 默认为0
print(z2)

tensor([1., 2., 3.])
tensor(1.)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1., 2., 3.])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[[-0.8189,  0.1821, -0.7314, -1.3146, -0.1625],
         [ 0.5218, -1.6122, -0.6681,  0.6638, -0.6357],
         [-1.5875,  0.5964,  0.8344,  1.5509,  1.8045],
         [ 1.0405, -0.2923,  0.7960, -0.7837,  0.4633]],

        [[-0.4234, -1.1919,  1.2405, -0.2928,  0.6935],
         [ 0.0583, -1.4217, -0.2596, -1.3041, -0.9261],
         [-0.3782,  1.1511,  1.5498, -0.9098,  1.3734],
         [-0.6867,  0.5426, -1.2608, -0.6211, -1.0209]],

        [[-0.0547,  2.7389,  0.1277,  0.3586, -0.6732],
         [-0.4873, -0.1533, -1.1152,  0.8455, -0.2956],
         [-1.2063, -0.5460,  0.8690, -0.5858, -0.0741],
         [ 0.3046, -0.7608,  0.3865,  0.7211,  0.5598]]])
tensor([5., 7., 9.])
tensor([[-4.4115e-01,  4.2064e-01,  5.3940e-01, -2.9033e-04,  5.8747e-01],
        [ 1

In [16]:
# Tensor 变形
x = torch.randn(2,3,4)
print(x)
print(x.view(2, 12))

tensor([[[-2.0133,  0.1762,  0.0236, -0.7760],
         [ 0.3458, -1.0979,  0.3646, -1.3126],
         [-0.5476, -0.5698,  0.4259,  1.1555]],

        [[ 2.0760, -1.0971,  0.6704, -0.8363],
         [ 0.0697, -0.9179,  0.5418,  0.0224],
         [-0.2133, -1.1332,  0.2417, -1.5240]]])
tensor([[-2.0133,  0.1762,  0.0236, -0.7760,  0.3458, -1.0979,  0.3646, -1.3126,
         -0.5476, -0.5698,  0.4259,  1.1555],
        [ 2.0760, -1.0971,  0.6704, -0.8363,  0.0697, -0.9179,  0.5418,  0.0224,
         -0.2133, -1.1332,  0.2417, -1.5240]])


In [25]:
# 计算图， tensor 无法在计算中记录自己的父级关系，需要使用变量 ‘variable’ 类型
# 从tensor中创建variable
import torch.autograd as autograd
x = autograd.Variable(torch.Tensor([1., 2., 3.]), requires_grad=True)
print(x.data)
# variable 支持tensor的所有运算
y = autograd.Variable(torch.Tensor([4., 5., 6.]), requires_grad=True)
z = x + y
print(z.data)     
# variable的特点就是，它在与你算中可以自动建立父子节点关系，知道是什么创建的
# 发现creator属性名称已经改为grad_fn，很多文档还未进行修改
s = z.sum()
print(s)
s.backward()
print(x.grad)
                    


tensor([1., 2., 3.])
tensor([5., 7., 9.])
tensor(21., grad_fn=<SumBackward0>)
tensor([1., 1., 1.])


In [28]:
# 仿射映射
import torch.nn as nn
lin = nn.Linear(5, 3)
# 2 行 5 列
data = autograd.Variable(torch.randn(2, 5))
print(data)
print(lin(data))

tensor([[-0.4512, -0.0879, -0.3940,  1.2367,  1.2519],
        [-0.3619,  1.0961,  0.7520, -0.2814, -0.3173]])
tensor([[ 0.7133, -0.8994,  0.5450],
        [ 0.2727, -0.0799,  0.3352]], grad_fn=<AddmmBackward>)


In [48]:
# 非线性函数
import torch.functional as F
data = autograd.Variable(torch.randn(2, 2))
print(data)
#新版本中的这两个激活函数已经放到了torch里
print(torch.relu(data))
print(torch.tanh(data))
# print(torch.sigmod(data))


tensor([[ 0.3032,  0.5010],
        [-1.6846,  1.4026]])
tensor([[0.3032, 0.5010],
        [0.0000, 1.4026]])
tensor([[ 0.2943,  0.4629],
        [-0.9335,  0.8859]])


In [47]:
data = autograd.Variable(torch.randn(5))
print(data)
print(torch.softmax(data, 0))
print(torch.softmax(data, 0).sum())

tensor([ 0.3730, -0.5866, -0.5673, -1.3969, -0.2648])
tensor([0.4045, 0.1549, 0.1579, 0.0689, 0.2138])
tensor(1.0000)
